// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3sRoqDt3MxTdEUw5i7ILPlNm6nM7NaEM',
    appId: '1:605475065236:web:c2f4556882f42293d71381',
    messagingSenderId: '605475065236',
    projectId: 'ecommerceapp-4d5ac',
    authDomain: 'ecommerceapp-4d5ac.firebaseapp.com',
    storageBucket: 'ecommerceapp-4d5ac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0eGLe_UoB97ZLH69S735PV6Gk-RdYMe4',
    appId: '1:605475065236:android:5de2e0a3a71b2715d71381',
    messagingSenderId: '605475065236',
    projectId: 'ecommerceapp-4d5ac',
    storageBucket: 'ecommerceapp-4d5ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByQpieuN2tP6XA68lUzYLI17KQEdmuRnU',
    appId: '1:605475065236:ios:ccc1e0a8f0bee03cd71381',
    messagingSenderId: '605475065236',
    projectId: 'ecommerceapp-4d5ac',
    storageBucket: 'ecommerceapp-4d5ac.appspot.com',
    androidClientId: '605475065236-m0qvtk405tn6o4s0c0bkf73dibhmcudq.apps.googleusercontent.com',
    iosClientId: '605475065236-gchosqlevjobeucqo6fvdmvac15od3oh.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByQpieuN2tP6XA68lUzYLI17KQEdmuRnU',
    appId: '1:605475065236:ios:ccc1e0a8f0bee03cd71381',
    messagingSenderId: '605475065236',
    projectId: 'ecommerceapp-4d5ac',
    storageBucket: 'ecommerceapp-4d5ac.appspot.com',
    androidClientId: '605475065236-m0qvtk405tn6o4s0c0bkf73dibhmcudq.apps.googleusercontent.com',
    iosClientId: '605475065236-gchosqlevjobeucqo6fvdmvac15od3oh.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3sRoqDt3MxTdEUw5i7ILPlNm6nM7NaEM',
    appId: '1:605475065236:web:7dd38bc2d8f44bd1d71381',
    messagingSenderId: '605475065236',
    projectId: 'ecommerceapp-4d5ac',
    authDomain: 'ecommerceapp-4d5ac.firebaseapp.com',
    storageBucket: 'ecommerceapp-4d5ac.appspot.com',
  );

}